site_name: Messaging Hub Client
pages:
- Visão Geral: index.md
- Configurações do Cliente: client-configuration.md
- Como Começar?: getting-started.md
- Comandos: commands.md
- Mensagens: messages.md
- Notificações: notifications.md
